### ISSUE TITLE
enhancement: Add Dependabot.yml to github

### ISSUE THREAD

**Issue by dailypush** [mcstatus-io/ping-server#4]
as a security and good practice there a free service on github called dependabot.
This service will check and make sure we are using the lastest versions and fixes for dependencies.
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

add a file in .github directory called dependabot.yml

```yml
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
```
